---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-project
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-dashboard

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-project
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-dashboard
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-dashboard
  name: github-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-project
subjects:
  - kind: ServiceAccount
    name: github-project
