---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-dashboard
  name: tekton-dashboard-tenant
  namespace: tekton-tenant
subjects:
  - kind: ServiceAccount
    name: tekton-dashboard
    namespace: openshift-pipelines
